In [3]:
import numpy as np
import time
import pandas as pd
#from keras.datasets import mnist

from keras.utils import to_categorical


from keras.models import Sequential

from keras.optimizers import SGD


from keras.layers import Input, Dense, Flatten, Dropout, Concatenate, Activation
#from keras.layers.normalization import BatchNormalization
from sklearn.model_selection import train_test_split
from keras.layers import *
from keras.callbacks import ModelCheckpoint, EarlyStopping

In [4]:
pip install keras

   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 11.9 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install tensorflow

   ---------------------------------------- 0.0/390.3 MB ? eta -:--:--
   ---------------------------------------- 1.8/390.3 MB 10.1 MB/s eta 0:00:39
   ---------------------------------------- 4.5/390.3 MB 11.2 MB/s eta 0:00:35
    --------------------------------------- 6.8/390.3 MB 11.3 MB/s eta 0:00:34
    --------------------------------------- 9.2/390.3 MB 11.4 MB/s eta 0:00:34
   - -------------------------------------- 11.8/390.3 MB 11.5 MB/s eta 0:00:33
   - -------------------------------------- 14.2/390.3 MB 11.5 MB/s eta 0:00:33
   - -------------------------------------- 16.5/390.3 MB 11.6 MB/s eta 0:00:33
   - -------------------------------------- 19.1/390.3 MB 11.6 MB/s eta 0:00:32
   -- ------------------------------------- 21.5/390.3 MB 11.7 MB/s eta 0:00:32
   -- ------------------------------------- 24.1/390.3 MB 11.7 MB/s eta 0:00:32
   -- ------------------------------------- 26.5/390.3 MB 11.7 MB/s eta 0:00:32
   -- ------------------------------------- 29.1/390.

In [234]:
train = pd.read_csv('train.csv', sep = ',')
test = pd.read_csv('test.csv', sep = ',')

In [235]:
train.head()

pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
0       59       43       50       68       98      119      139      145   
1      154      126      105      102      125      155      172      180   
2      255      253      253      253      253      253      253      253   
3       28       37       38       42       44       40       40       24   
4      170      168      177      183      181      177      181      184   

   pixel_8  pixel_9  ...  pixel_3063  pixel_3064  pixel_3065  pixel_3066  \
0      149      149  ...          58          65          59          46   
1      142      111  ...          42          67         101         122   
2      253      253  ...          83          80          69          66   
3       32       43  ...          39          59          42          44   
4      189      189  ...          88          85          82          83   

   pixel_3067  pixel_3068  pixel_3069  pixel_3070  pixel_3071  label  
0          57         104         140          84          72      6  
1         133         136         139         142         144      9  
2          72          79          83          83          84      9  
3          48          38          28          37          46      4  
4          79          78          82          78          80      1  

[5 rows x 3073 columns]

In [236]:
test.head()

pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
0      158      159      165      166      160      156      162      159   
1      235      231      232      232      232      232      232      232   
2      158      158      139      132      166      182      187      193   
3      155      167      176      190      177      166      168      166   
4       65       70       48       30       23       40       44       45   

   pixel_8  pixel_9  ...  pixel_3062  pixel_3063  pixel_3064  pixel_3065  \
0      158      159  ...         130         123         145         167   
1      232      232  ...         108         117         123         133   
2      199      205  ...          45          46          44          44   
3      170      179  ...          52          55          70         103   
4       45       40  ...         102         127         156         139   

   pixel_3066  pixel_3067  pixel_3068  pixel_3069  pixel_3070  pixel_3071  
0         182         175         145         124         129         110  
1         141         153         163         178         191         199  
2          43          52          37           8           3           7  
3         105          72          53          50          52          50  
4         131         130         147         136         146         117  

[5 rows x 3072 columns]

In [240]:
np.shape(train) , np.shape(test)

((50000, 3073), (10000, 3072))

In [242]:
y_train = train['label']

In [244]:
train['label'].unique()

array([6, 9, 4, 1, 2, 7, 8, 3, 5, 0], dtype=int64)

In [246]:
x_train = train.drop(columns = ['label'])

In [247]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size = 0.3, shuffle = True)
x_test, x_val, y_test, y_val = train_test_split(x_test, y_test, test_size = 0.5, shuffle = True)

In [348]:
np.shape(x_train), np.shape(x_test), np.shape(x_val) , np.shape(y_train)

((35000, 3072), (7500, 3072), (7500, 3072), (35000,))

In [274]:
def counter_classes(target):
    for i in range(0, 10) :
        print(f"le nombre d'éléments dans la classe {i} est : {(target == i).sum()*100/len(target) : .2f}%") 

In [276]:
counter_classes(y_train)

le nombre d'éléments dans la classe 0 est :  10.10%
le nombre d'éléments dans la classe 1 est :  9.92%
le nombre d'éléments dans la classe 2 est :  9.98%
le nombre d'éléments dans la classe 3 est :  9.98%
le nombre d'éléments dans la classe 4 est :  9.90%
le nombre d'éléments dans la classe 5 est :  10.08%
le nombre d'éléments dans la classe 6 est :  10.06%
le nombre d'éléments dans la classe 7 est :  9.88%
le nombre d'éléments dans la classe 8 est :  9.92%
le nombre d'éléments dans la classe 9 est :  10.18%


In [278]:
counter_classes(y_test)

le nombre d'éléments dans la classe 0 est :  9.56%
le nombre d'éléments dans la classe 1 est :  10.29%
le nombre d'éléments dans la classe 2 est :  9.96%
le nombre d'éléments dans la classe 3 est :  9.79%
le nombre d'éléments dans la classe 4 est :  10.52%
le nombre d'éléments dans la classe 5 est :  9.97%
le nombre d'éléments dans la classe 6 est :  10.13%
le nombre d'éléments dans la classe 7 est :  10.13%
le nombre d'éléments dans la classe 8 est :  10.25%
le nombre d'éléments dans la classe 9 est :  9.39%


In [280]:
#normalization(mix max scaler :  max = 255 and min = 0)
x_train /= 255
x_test /= 255
x_val /= 255

In [ ]:
#One-Hot Encoding
Y_train = to_categorical(y_train, 10)
Y_test = to_categorical(y_test, 10)
Y_val = to_categorical(y_val, 10)

In [350]:
Y_train.shape

(35000, 10)

In [ ]:
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
x_val = x_val.to_numpy()

In [286]:
np.shape(x_val)

(7500, 3072)

In [288]:
X_train = x_train.reshape(x_train.shape[0], 32, 32, 3) #  1 2 0
X_test = x_test.reshape(x_test.shape[0], 32, 32, 3)
X_val = x_val.reshape(x_val.shape[0], 32, 32, 3)

In [290]:
X_val[0]

array([[[0.21176471, 0.22745098, 0.50588235],
        [0.64313725, 0.68235294, 0.77254902],
        [0.58039216, 0.18823529, 0.27058824],
        ...,
        [0.45490196, 0.54901961, 0.45098039],
        [0.74901961, 0.87058824, 0.82745098],
        [0.79607843, 0.67843137, 0.6       ]],

       [[0.24313725, 0.31764706, 0.55686275],
        [0.67843137, 0.71764706, 0.78823529],
        [0.58039216, 0.16078431, 0.21176471],
        ...,
        [0.46666667, 0.47843137, 0.63529412],
        [0.85882353, 0.82352941, 0.82352941],
        [0.79607843, 0.72156863, 0.58039216]],

       [[0.27843137, 0.35294118, 0.58039216],
        [0.69803922, 0.73333333, 0.78823529],
        [0.56470588, 0.18431373, 0.24313725],
        ...,
        [0.4       , 0.40784314, 0.43529412],
        [0.55294118, 0.78039216, 0.82352941],
        [0.82352941, 0.78039216, 0.65098039]],

       ...,

       [[0.39215686, 0.39607843, 0.40784314],
        [0.41568627, 0.41960784, 0.41568627],
        [0.40392157, 0

In [292]:
X_val.shape

(7500, 32, 32, 3)

In [328]:
num_epochs = 400
batch_size = 4

model = Sequential()

model.add(Conv2D(64, kernel_size = (3,3), activation = 'relu', input_shape = (32, 32, 3), padding = 'same', strides = 1))
model.add(MaxPooling2D((2,2), padding = 'same'))
model.add(Dropout(0.2))

model.add(Conv2D(128, kernel_size = (3, 3), activation = 'relu', padding = 'same'))
model.add(MaxPooling2D((2,2), padding = 'same'))
model.add(Dropout(0.3))

model.add(Flatten())
model.add(Dense(120, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

checkpointer = ModelCheckpoint(filepath = 'CNN_model_cifar.keras', monitor = 'val_loss', verbose = 0, save_best_only = True, save_weights_only = False,
                               mode = 'min', save_freq=1)
early = EarlyStopping(monitor = 'val_loss', min_delta = 0, patience = 8, verbose = 0, mode = 'auto') # min_delta = 0, ce qui signifie que toute amélioration, même minime, est suffisante pour continuer.

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy']) 

history = model.fit(X_train, Y_train, epochs = num_epochs, batch_size = batch_size, validation_data = (X_val, Y_val), callbacks = [checkpointer, early])

C:\Users\hp\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/400
  19/8750 ━━━━━━━━━━━━━━━━━━━━ 1:24 10ms/step - accuracy: 0.0738 - loss: 2.4390 

C:\Users\hp\anaconda3\Lib\site-packages\keras\src\callbacks\model_checkpoint.py:199: UserWarning: Can save best model only with val_loss available, skipping.
  self._save_model(epoch=self._current_epoch, batch=batch, logs=logs)


8750/8750 ━━━━━━━━━━━━━━━━━━━━ 91s 10ms/step - accuracy: 0.3366 - loss: 1.8060 - val_accuracy: 0.4860 - val_loss: 1.4390
Epoch 2/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 85s 10ms/step - accuracy: 0.5064 - loss: 1.3915 - val_accuracy: 0.5395 - val_loss: 1.3156
Epoch 3/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 85s 10ms/step - accuracy: 0.5487 - loss: 1.2641 - val_accuracy: 0.5453 - val_loss: 1.2752
Epoch 4/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 88s 10ms/step - accuracy: 0.5757 - loss: 1.2001 - val_accuracy: 0.5756 - val_loss: 1.2163
Epoch 5/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 90s 10ms/step - accuracy: 0.5930 - loss: 1.1506 - val_accuracy: 0.5721 - val_loss: 1.2239
Epoch 6/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 90s 10ms/step - accuracy: 0.6151 - loss: 1.0925 - val_accuracy: 0.5864 - val_loss: 1.1880
Epoch 7/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 88s 10ms/step - accuracy: 0.6223 - loss: 1.0684 - val_accuracy: 0.5871 - val_loss: 1.1770
Epoch 8/400
8750/8750 ━━━━━━━━━━━━━━━━━━━━ 93s 11ms/step - accuracy: 0.6410 - los

In [324]:
y_pred = model.predict(X_test)

235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step


In [326]:
model.evaluate(X_test, Y_test)

235/235 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6142 - loss: 1.1790


[1.1965242624282837, 0.6050666570663452]

In [298]:
from sklearn.metrics import log_loss, accuracy_score , precision_score, recall_score, f1_score, confusion_matrix

In [300]:
y_test_classes = np.argmax(Y_test, axis=1)
y_pred_classes = np.argmax(y_pred, axis=1)  

In [304]:
loss = log_loss(Y_test, y_pred)
loss

1.1321116047534563

In [228]:
accuracy = accuracy_score(y_test_classes, y_pred_classes)
accuracy

0.6666666666666666

In [308]:
cm = confusion_matrix(y_test_classes, y_pred_classes)
cm

array([[390,  19,  72,  20,  24,  13,  20,  39,  64,  56],
       [ 11, 550,   8,  11,  13,   9,  41,  10,  23,  96],
       [ 18,   1, 386,  43,  60,  75, 101,  44,   7,  12],
       [ 10,   8,  56, 236,  46, 172, 123,  52,   6,  25],
       [  8,   4,  94,  37, 390,  48, 104,  92,   7,   5],
       [  5,   6,  38, 108,  31, 427,  52,  62,   7,  12],
       [  6,   6,  38,  45,  41,  27, 577,   9,   1,  10],
       [  8,   5,  18,  30,  44,  52,  26, 557,   3,  17],
       [ 48,  43,  31,  16,  13,  12,  19,  12, 547,  28],
       [ 12,  96,   6,  17,   8,  17,  25,  17,  24, 482]], dtype=int64)

In [310]:
precision = precision_score(y_test_classes, y_pred_classes, average = 'macro')
precision

0.6116250213458225

In [312]:
recall = recall_score(y_test_classes, y_pred_classes, average = 'macro')
recall

0.6047857715188681

In [314]:
f1_score = f1_score(y_test_classes, y_pred_classes, average = 'macro')

In [316]:
f1_score

0.6024619803724975